// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: track_repository.sql

package postgres

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  lineid,name,month_limit,created_at,updated_at
) VALUES (
  $1,$2,$3,$4,$5
)
RETURNING id, lineid, name, month_limit, created_at, updated_at
`

type CreateUserParams struct {
	Lineid     string    `json:"lineid"`
	Name       string    `json:"name"`
	MonthLimit int32     `json:"month_limit"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Lineid,
		arg.Name,
		arg.MonthLimit,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Lineid,
		&i.Name,
		&i.MonthLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
